---
port: 4000
debug: True

# Signed Cookies. Generate a new key with:
# python -c "from os import urandom; from base64 import b64encode; print(b64encode(urandom(16)).decode('utf-8'))"
secret_key: 'C7HgDjLdF+nIMvQiAa5yzA=='

user_registration_api: False
users:
    - user1: {'login': '', 'pass': ''}
    - user2: {'login': '', 'pass': ''}

PostgreSQL:
    conn_string: 'db_user:db_pw@localhost:5432/db_name'
MySQL:
    conn_string: 'db_user:db_pw@localhost:3306/db_name'
...
